name: Freezer
version: 1.0.0
author: damo1995]
api-version: 1.13.0
main: uk.co.ddelay.freezer.Freezer
commands:
   freeze:
       description: 'Freeze a selected player'
       usage: /freeze [player]